###viewListOfAvailable coins
GET http://localhost:8080/coins/available
Accept: application/json

###findAll coins
GET http://localhost:8080/coins/
Accept: application/json

###findBySymbol coin
GET http://localhost:8080/coins/bySymbol/BTC
Accept: application/json

###getPriceFromCoinLore coin
GET http://localhost:8080/coins/getPriceFromCoinLore/90
Accept: application/json

###save user
POST http://localhost:8080/users?userName=Pavel&symbol=BTC
Content-Type: application/json