###viewListOfAvailable coins
GET http://localhost:8085/coins
Accept: application/json

###findBySymbol coin
GET http://localhost:8085/coins/BTC
Accept: application/json

###findAllUsers coin
GET http://localhost:8085/users
Accept: application/json

###save user#1
POST http://localhost:8085/users?userName=Pavel&symbol=BTC&id=25464646464
Content-Type: application/json

###save user#2
POST http://localhost:8085/users?userName=Nikita&symbol=ETH&id=278864
Content-Type: application/json

###save user#3
POST http://localhost:8085/users?userName=Sergio&symbol=SOL&id=986434664
Content-Type: application/json